import { Link } from "@tanstack/react-router";
import { KeyRound } from "lucide-react";

import { BiasBadge, SourceTag } from "@/components/market/badges";
import { Skeleton } from "@/components/ui/skeleton";
import type { MarketAnalysis, Scenario } from "@/types/market";
import { cn } from "@/lib/utils";

const scenarioTone = {
  bullish: "border-bull/30 bg-bull/5",
  bearish: "border-bear/30 bg-bear/5",
  neutral: "border-info/30 bg-info/5",
};

export function ScenarioCard({ scenario }: { scenario: Scenario }) {
  return (
    <div className={cn("rounded-md border p-3", scenarioTone[scenario.type])}>
      <div className="flex items-center justify-between gap-2">
        <p className="text-sm font-medium text-foreground">{scenario.title}</p>
        <span className="num text-xs text-muted-foreground">{Math.round(scenario.probability * 100)}%</span>
      </div>
      <p className="mt-2 text-xs text-muted-foreground">
        <span className="font-medium text-foreground/80">Trigger: </span>
        {scenario.trigger}
      </p>
      <p className="mt-1 text-xs text-muted-foreground">
        <span className="font-medium text-foreground/80">Outcome: </span>
        {scenario.outcome}
      </p>
    </div>
  );
}

function List({ title, items }: { title: string; items: string[] }) {
  return (
    <div>
      <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{title}</p>
      <ul className="mt-2 space-y-1.5">
        {items.map((item) => (
          <li key={item} className="flex gap-2 text-sm text-foreground/90">
            <span className="mt-1.5 size-1 shrink-0 rounded-full bg-muted-foreground" aria-hidden />
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

export function AnalysisCard({
  analysis,
  loading,
  needsKey = false,
  title = "AI Market Overview",
  showUsdContext = false,
}: {
  analysis?: MarketAnalysis | null | undefined;
  loading?: boolean | undefined;
  needsKey?: boolean | undefined;
  title?: string | undefined;
  showUsdContext?: boolean | undefined;
}) {
  return (
    <section className="panel p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <h2 className="text-sm font-semibold text-foreground">{title}</h2>
          {analysis?.sample ? <SourceTag label="Sample analysis" /> : null}
        </div>
        {analysis ? (
          <div className="flex items-center gap-3">
            <BiasBadge bias={analysis.bias} />
            <span className="num text-xs text-muted-foreground">
              confidence {Math.round(analysis.confidence * 100)}%
            </span>
          </div>
        ) : null}
      </div>

      {needsKey ? (
        <div className="mt-4 flex flex-col items-start gap-2 rounded-md border border-dashed border-border p-4">
          <p className="flex items-center gap-2 text-sm text-foreground/90">
            <KeyRound className="size-4 text-gold" />
            No AI key configured — this overview is generated by a real AI provider, not mock data.
          </p>
          <p className="text-xs text-muted-foreground">
            Add a free Gemini key (or OpenAI / Anthropic) in{" "}
            <Link to="/settings" className="text-primary hover:underline">
              Settings
            </Link>{" "}
            and this panel will analyze this week's real calendar.
          </p>
        </div>
      ) : loading || !analysis ? (
        <div className="mt-4 space-y-3">
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-11/12" />
          <Skeleton className="h-24 w-full" />
        </div>
      ) : (
        <>
          <p className="mt-4 text-sm leading-relaxed text-foreground/90">{analysis.summary}</p>

          <div className="mt-5 grid gap-6 md:grid-cols-2">
            <List title="Key drivers" items={analysis.keyDrivers} />
            <List title="Main risks" items={analysis.mainRisks} />
          </div>

          {showUsdContext ? (
            <div className="mt-5 rounded-md border border-border bg-background/40 p-3">
              <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">USD context</p>
              <p className="mt-1.5 text-sm text-foreground/90">{analysis.usdContext}</p>
            </div>
          ) : null}

          <div className="mt-5 grid gap-3 md:grid-cols-3">
            {analysis.scenarios.map((scenario) => (
              <ScenarioCard key={scenario.title} scenario={scenario} />
            ))}
          </div>

          <p className="mt-5 border-t border-border pt-3 text-xs text-muted-foreground">
            {analysis.sample
              ? "Generated as a local sample — no AI provider is connected."
              : "Generated by your configured AI provider from this week's real calendar."}{" "}
            This is not financial advice and must not be used for trading decisions.
          </p>
        </>
      )}
    </section>
  );
}
