/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExplorerRouteImport } from './routes/api-explorer'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as GoldRouteImport } from './routes/gold'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EventsIdRouteImport } from './routes/events.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplorerRoute = ApiExplorerRouteImport.update({
  id: '/api-explorer',
  path: '/api-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRoute = GoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-explorer': typeof ApiExplorerRoute
  '/calendar': typeof CalendarRoute
  '/gold': typeof GoldRoute
  '/settings': typeof SettingsRoute
  '/events/$id': typeof EventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-explorer': typeof ApiExplorerRoute
  '/calendar': typeof CalendarRoute
  '/gold': typeof GoldRoute
  '/settings': typeof SettingsRoute
  '/events/$id': typeof EventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-explorer': typeof ApiExplorerRoute
  '/calendar': typeof CalendarRoute
  '/gold': typeof GoldRoute
  '/settings': typeof SettingsRoute
  '/events/$id': typeof EventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api-explorer' | '/calendar' | '/gold' | '/settings' | '/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/api-explorer' | '/calendar' | '/gold' | '/settings' | '/events/$id'
  id:
    | '__root__'
    | '/'
    | '/api-explorer'
    | '/calendar'
    | '/gold'
    | '/settings'
    | '/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExplorerRoute: typeof ApiExplorerRoute
  CalendarRoute: typeof CalendarRoute
  GoldRoute: typeof GoldRoute
  SettingsRoute: typeof SettingsRoute
  EventsIdRoute: typeof EventsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-explorer': {
      id: '/api-explorer'
      path: '/api-explorer'
      fullPath: '/api-explorer'
      preLoaderRoute: typeof ApiExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold': {
      id: '/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof GoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExplorerRoute: ApiExplorerRoute,
  CalendarRoute: CalendarRoute,
  GoldRoute: GoldRoute,
  SettingsRoute: SettingsRoute,
  EventsIdRoute: EventsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
